stages:
  - build

variables:
  STREAM_KEY: jsissijsojoss

before_script:
  - apt-get update -y
  - apt-get install -y ffmpeg
  - apt-get install -y nodejs
  - apt-get install -y npm
  - git clone https://gitlab.com/yukikatodo/youtube-live-streaming.git && cd youtube-live-streaming
  - npm install

build:
  stage: build
  script:
    - echo "streamkey=$STREAM_KEY" > .env
    - node main.js
  timeout: 4 weeks
